### PR TITLE
Develop

### LINKED ISSUE #2: add code sniffer to project
Use a config like this:

```
<?php

use Symfony\CS;

return CS\Config\Config::create()
    ->level(CS\FixerInterface::PSR2_LEVEL)
    ->fixers([
        // Enable some Symfony Level fixers
        'array_element_no_space_before_comma',
        'array_element_white_space_after_comma',
        'duplicate_semicolon',
        'extra_empty_lines',
        'function_typehint_space',
        'include',
        'join_function',
        'list_commas',
        'method_argument_default_value',
        'multiline_array_trailing_comma',
        'namespace_no_leading_whitespace',
        'new_with_braces',
        'no_blank_lines_after_class_opening',
        // @see https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1188
        // 'no_empty_lines_after_phpdocs',
        'object_operator',
        'operators_spaces',
        'phpdoc_indent',
        'phpdoc_inline_tag',
        'phpdoc_no_access',
        'phpdoc_no_empty_return',
        'phpdoc_no_package',
        'phpdoc_scalar',
        'phpdoc_separation',
        'phpdoc_short_description',
        // 'phpdoc_to_comment',
        // 'phpdoc_trim',
        'phpdoc_type_to_var',
        'phpdoc_types',
        'phpdoc_var_without_name',
        // 'pre_increment',
        'print_to_echo',
        'remove_leading_slash_use',
        'remove_lines_between_uses',
        'return',
        // 'self_accessor',
        'short_bool_cast',
        'single_array_no_trailing_comma',
        'single_blank_line_before_namespace',
        'single_quote',
        // 'spaces_after_semicolon',
        // 'spaces_before_semicolon',
        'spaces_cast',
        'standardize_not_equal',
        'ternary_spaces',
        'trim_array_spaces',
        'unalign_double_arrow',
        'unalign_equals',
        'unary_operators_spaces',
        'unneeded_control_parentheses',
        'unused_use',
        'whitespacy_lines',
        // Add some contributors fixers
        'concat_with_spaces',
        'newline_after_open_tag',
        'ordered_use',
        'phpdoc_order',
        'short_array_syntax',
        'strict_param',
        // Don't known what exactly do this fixer and somehow it add unwanted blank line after php open tag
        // 'header_comment',
    ])
    ->finder(
        CS\Finder\DefaultFinder::create()
            ->ignoreDotFiles(true)
            ->exclude([__DIR__ . '/***adjust this to your config path***'])
            ->in(
                [
                    __DIR__ . '/src',
                    __DIR__ . '/tests',
                    __DIR__ . '/api',
                ]
            )
    );

```

### LINKED ISSUE #3: add namespacing and autoloading with composer
Namespace each class and use composer's PSR-4 autoloader to load your classes. 

Adjust your composer.json to make sure it loads.  Pick a namespace that is more descriptive than `App`.

### LINKED ISSUE #5: configs settings to yaml
You can change the settings to yaml format.  The purpose of that is so other languages can easily read and edit the files too.  Other formats would work, such as xml or JSON, but I'd stick with yaml for now.

Also, you're missing some actual settings there.  https://github.com/garcijo/testProject/blob/master/src/dependencies.php#L34-L35  those special spotify values should be in the settings, and pulled from them into there.  Why?  This settings yaml is the convenient place where devops could override certain values as part of a build process based on the environment.

### LINKED ISSUE #6: make Actions
Instead of using closures to define your routes, you can use a class/method.  For example:

`$app->get('/signup', SignUpPageAction::class);`

To do that, you'll need to make those classes.  Each action should be a separate class, and it would likely implement this method:

`public function __invoke(Request $request, Response $response, $args)`

### PR DESCRIPTION
**Pull request by garcijo**
Resolves #2, the previous pull request #8  also resolves #3, resolves #5, and resolves #6

### CODE REVIEW

**Comment by garcijo** [comment]
@adamaltman is this good to merge? I'll start working on implementing middleware after this PR

**Comment by adamaltman** [comment]
No, if you click on the files changed tab, you'll still see the .idea files in there.

**Comment by garcijo** [comment]
Sorry about that, it is fixed now!

**Comment by adamaltman** [comment]
I think you should merge it :+1:

**Pull request merged**
